export const actionTypes = {
    LOADING_START: 'LOADING_START',
    LOADING_STOP: 'LOADING_STOP',
    GET_POKEMON_SUCCESS: 'GET_POKEMON_SUCCESS',
    GET_POKEMON_FAILURE: 'GET_POKEMON_FAILURE',
    SEARCH_POKEMON_SUCCESS: 'SEARCH_POKEMON_SUCCESS',
    SEARCH_POKEMON_FAILURE : 'SEARCH_POKEMON_FAILURE',
    MY_TEAM_POKEMON: 'MY_TEAM_POKEMON',
    POKEMON_DETAILS_SUCCESS : 'POKEMON_DETAILS_SUCCESS',
    POKEMON_DETAILS_FAILURE : 'POKEMON_DETAILS_FAILURE'
}